/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGuidesIndexRouteImport } from './routes/_app.guides.index'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppGuidesNewRouteImport } from './routes/_app.guides.new'
import { Route as AppGuidesGuideIdRouteImport } from './routes/_app.guides.$guideId'
import { Route as AppChatFriendIdRouteImport } from './routes/_app.chat.$friendId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesIndexRoute = AppGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesNewRoute = AppGuidesNewRouteImport.update({
  id: '/guides/new',
  path: '/guides/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesGuideIdRoute = AppGuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatFriendIdRoute = AppChatFriendIdRouteImport.update({
  id: '/chat/$friendId',
  path: '/chat/$friendId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/friends': typeof AppFriendsRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/chat/$friendId': typeof AppChatFriendIdRoute
  '/guides/$guideId': typeof AppGuidesGuideIdRoute
  '/guides/new': typeof AppGuidesNewRoute
  '/chat/': typeof AppChatIndexRoute
  '/guides/': typeof AppGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/friends': typeof AppFriendsRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/chat/$friendId': typeof AppChatFriendIdRoute
  '/guides/$guideId': typeof AppGuidesGuideIdRoute
  '/guides/new': typeof AppGuidesNewRoute
  '/chat': typeof AppChatIndexRoute
  '/guides': typeof AppGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/map': typeof AppMapRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/chat/$friendId': typeof AppChatFriendIdRoute
  '/_app/guides/$guideId': typeof AppGuidesGuideIdRoute
  '/_app/guides/new': typeof AppGuidesNewRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/guides/': typeof AppGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/friends'
    | '/map'
    | '/profile'
    | '/chat/$friendId'
    | '/guides/$guideId'
    | '/guides/new'
    | '/chat/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/friends'
    | '/map'
    | '/profile'
    | '/chat/$friendId'
    | '/guides/$guideId'
    | '/guides/new'
    | '/chat'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/friends'
    | '/_app/map'
    | '/_app/profile'
    | '/_app/chat/$friendId'
    | '/_app/guides/$guideId'
    | '/_app/guides/new'
    | '/_app/chat/'
    | '/_app/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides/': {
      id: '/_app/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof AppGuidesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides/new': {
      id: '/_app/guides/new'
      path: '/guides/new'
      fullPath: '/guides/new'
      preLoaderRoute: typeof AppGuidesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides/$guideId': {
      id: '/_app/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof AppGuidesGuideIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$friendId': {
      id: '/_app/chat/$friendId'
      path: '/chat/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof AppChatFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppMapRoute: typeof AppMapRoute
  AppProfileRoute: typeof AppProfileRoute
  AppChatFriendIdRoute: typeof AppChatFriendIdRoute
  AppGuidesGuideIdRoute: typeof AppGuidesGuideIdRoute
  AppGuidesNewRoute: typeof AppGuidesNewRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppGuidesIndexRoute: typeof AppGuidesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppMapRoute: AppMapRoute,
  AppProfileRoute: AppProfileRoute,
  AppChatFriendIdRoute: AppChatFriendIdRoute,
  AppGuidesGuideIdRoute: AppGuidesGuideIdRoute,
  AppGuidesNewRoute: AppGuidesNewRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppGuidesIndexRoute: AppGuidesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
